version: "3.7"
services:
  mongo:
    image: mongo:5.0.11
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - /etc/mongo:/data/db